Initial version
adafruit/Adafruit_CircuitPython_STMPE610 pull request #1
Opened 2018-04-23 19:53 UTC by jerryneedell

This is the initial version of a driver for the STMPE 610 Resistive Touch Screen Controller.

It supports both SPI and I2C.

For SPI - I have not yet addressed the issue reported by @ladyada  where on some occasions, the wrong clock edge gets used. I have only seen this very rarely and I'm still thinking about how to handle it. Usually, just retrying fixes it.

as suggested, this is patterned "loosely" after the FocalTouch driver.

For the "touches" method, I arbitrarily allow it to return up to 4 touches at at time. The controller buffer can hold 128, but it is easy to run out of memory. I the paint demo, it never needs to buffer more than 1 anyway.  Not sure if the buffering is useful or not, put it in as an example.

I have tested it on a 2.4inch TFT featherwing (SPI) and on a feather_m0_express with an stmpe610 breakout and touchscreen (PID 333) with SPI and I2C.

The paint demo has been tested on a 2.4 inch TFT Featherwing via a feather52 but the code in the repo is set up for feather_m0_express pins.

Comments welcome.

2018-04-24 19:38 UTC, tannewt requested changes
Thanks @jerryneedell ! I added a few comments.

2018-04-24 19:38 UTC, tannewt commented on adafruit_stmpe610.py
> +    # pylint: disable=unused-variable
What is unused?

2018-04-24 19:38 UTC, tannewt commented on adafruit_stmpe610.py
> +STMPE_TSC_CFG_SETTLE_100MS = const(0x07)
Do all of these need to be public? If you prefix them with _ they'll be omitted from the mpy and save memory when loaded.

2018-04-24 19:38 UTC, tannewt commented on examples/stmpe610_simpletest.py
> +print("Go Ahead - Touch the Screen - Make My Day!")
:-)

2018-04-24 19:38 UTC, tannewt commented on adafruit_stmpe610.py
> +__repo__ = "https://github.com/adafruit/Adafruit_CircuitPython_stmpe610.git"
I believe STMPE should be capitalized to match the github repo name.

2018-04-24 19:38 UTC, tannewt commented on README.rst
> +see examples in githup repository: https://github.com/adafruit/Adafruit_CIrcuitPython_STMPE610/exmaples
Mis-capitalization in `CIrcuitPython`

2018-04-25 10:13 UTC, jerryneedell commented on adafruit_stmpe610.py
> +__repo__ = "https://github.com/adafruit/Adafruit_CircuitPython_stmpe610.git"
Thanks - will change

2018-04-25 10:13 UTC, jerryneedell commented on README.rst
> +see examples in githup repository: https://github.com/adafruit/Adafruit_CIrcuitPython_STMPE610/exmaples
argh. Thanks.

2018-04-27 21:56 UTC, tannewt approved these changes

2018-04-27 21:56 UTC, tannewt commented
Thank you @jerryneedell !

2018-04-27 21:56 UTC, merged